-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 13:39:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `sinopsis` MEDIUMTEXT NOT NULL,
  `anio` INT NOT NULL,
  `generos_id` INT NOT NULL,
  `contenidoimagen` LONGBLOB NOT NULL,
  `tipoimagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peliculas_generos1_idx` (`generos_id` ASC),
  CONSTRAINT `fk_peliculas_generos1`
    FOREIGN KEY (`generos_id`)
    REFERENCES `generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreusuario` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `administrador` TINYINT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `fecha` DATE NOT NULL,
  `peliculas_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `calificacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_peliculas1_idx` (`peliculas_id` ASC),
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_comentarios_peliculas1`
    FOREIGN KEY (`peliculas_id`)
    REFERENCES `peliculas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
